FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o ingestion ./cmd/ingestion/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/ingestion .
EXPOSE 50051 8080
CMD ["./ingestion"]
