/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#9f0519",
        "surface-variant": "#192540",
        "on-primary-container": "#004f24",
        "surface-dim": "#060e20",
        "inverse-on-surface": "#4d556b",
        "surface-container-highest": "#192540",
        "inverse-primary": "#006e35",
        "on-secondary-container": "#fff6ec",
        "primary-container": "#13ea79",
        "primary-dim": "#24f07e",
        "on-tertiary": "#490006",
        "tertiary-container": "#f94d4e",
        "tertiary": "#ff716c",
        "surface-tint": "#3fff8b",
        "tertiary-fixed-dim": "#ff7b75",
        "primary-fixed": "#3fff8b",
        "tertiary-dim": "#ff716c",
        "primary": "#3fff8b",
        "on-surface": "#dee5ff",
        "error": "#ff716c",
        "on-surface-variant": "#a3aac4",
        "background": "#060e20",
        "secondary-container": "#785900",
        "surface-container": "#0f1930",
        "tertiary-fixed": "#ff928c",
        "on-secondary": "#553e00",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#091328",
        "outline-variant": "#40485d",
        "on-secondary-fixed": "#443100",
        "on-tertiary-fixed": "#3a0004",
        "on-primary-fixed-variant": "#006832",
        "secondary-fixed-dim": "#f7ba00",
        "surface-bright": "#1f2b49",
        "secondary-fixed": "#ffca4d",
        "secondary": "#fdc003",
        "on-background": "#dee5ff",
        "on-error": "#490006",
        "on-error-container": "#ffa8a3",
        "inverse-surface": "#faf8ff",
        "outline": "#6d758c",
        "error-dim": "#d7383b",
        "secondary-dim": "#ecb200",
        "surface": "#060e20",
        "on-primary": "#005d2c",
        "on-tertiary-fixed-variant": "#790010",
        "on-secondary-fixed-variant": "#674c00",
        "on-tertiary-container": "#110000",
        "surface-container-high": "#141f38",
        "on-primary-fixed": "#004820",
        "primary-fixed-dim": "#24f07e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      }
    },
  },
  plugins: [],
}
