// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/v1/telemetry.proto

package telemetryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSignal) Reset() {
	*x = DeviceSignal{}
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSignal) ProtoMessage() {}

func (x *DeviceSignal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSignal.ProtoReflect.Descriptor instead.
func (*DeviceSignal) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceSignal) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceSignal) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DeviceSignal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *DeviceSignal          `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryRequest) GetSignal() *DeviceSignal {
	if x != nil {
		return x.Signal
	}
	return nil
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_v1_telemetry_proto protoreflect.FileDescriptor

const file_api_proto_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/telemetry.proto\x12\ftelemetry.v1\"_\n" +
	"\fDeviceSignal\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"F\n" +
	"\x10TelemetryRequest\x122\n" +
	"\x06signal\x18\x01 \x01(\v2\x1a.telemetry.v1.DeviceSignalR\x06signal\"G\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2d\n" +
	"\x10TelemetryService\x12P\n" +
	"\rSendTelemetry\x12\x1e.telemetry.v1.TelemetryRequest\x1a\x1f.telemetry.v1.TelemetryResponseB8Z6github.com/jules/sentinelstream/pkg/api/v1;telemetryv1b\x06proto3"

var (
	file_api_proto_v1_telemetry_proto_rawDescOnce sync.Once
	file_api_proto_v1_telemetry_proto_rawDescData []byte
)

func file_api_proto_v1_telemetry_proto_rawDescGZIP() []byte {
	file_api_proto_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_telemetry_proto_rawDesc), len(file_api_proto_v1_telemetry_proto_rawDesc)))
	})
	return file_api_proto_v1_telemetry_proto_rawDescData
}

var file_api_proto_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_v1_telemetry_proto_goTypes = []any{
	(*DeviceSignal)(nil),      // 0: telemetry.v1.DeviceSignal
	(*TelemetryRequest)(nil),  // 1: telemetry.v1.TelemetryRequest
	(*TelemetryResponse)(nil), // 2: telemetry.v1.TelemetryResponse
}
var file_api_proto_v1_telemetry_proto_depIdxs = []int32{
	0, // 0: telemetry.v1.TelemetryRequest.signal:type_name -> telemetry.v1.DeviceSignal
	1, // 1: telemetry.v1.TelemetryService.SendTelemetry:input_type -> telemetry.v1.TelemetryRequest
	2, // 2: telemetry.v1.TelemetryService.SendTelemetry:output_type -> telemetry.v1.TelemetryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_telemetry_proto_init() }
func file_api_proto_v1_telemetry_proto_init() {
	if File_api_proto_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_telemetry_proto_rawDesc), len(file_api_proto_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_telemetry_proto_msgTypes,
	}.Build()
	File_api_proto_v1_telemetry_proto = out.File
	file_api_proto_v1_telemetry_proto_goTypes = nil
	file_api_proto_v1_telemetry_proto_depIdxs = nil
}
